name: bady333-A26

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: UbuntuWSL-16GB-8C-2048GB
    steps:
      - name: Install the build packages
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt -y install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git git-lfs gnupg gperf imagemagick protobuf-compiler python3-protobuf lib32readline-dev lib32z1-dev libdw-dev libelf-dev lz4 libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev

      - name: Initialize the bady333 source repository
        run: |
          cd ~/bady333/Lineage
          repo init --depth=1 --no-repo-verify --git-lfs -u https://github.com/LineageOS/android.git -b lineage-23.0

      - name: Prepare the device-specific code
        run: |
          cd ~/bady333/Lineage
          mkdir -p .repo/local_manifests
          curl -o .repo/local_manifests/roomservice.xml https://raw.githubusercontent.com/bady333/LineageOS-a26/refs/heads/main/manifest/roomservice-a266b.xml
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          source build/envsetup.sh
      
      - name: Configure git
        run: |
          git config --global user.email bad.workapi@gmail.com
          git config --global user.name bady333
      
      - name: Build bady333
        run: |
          cd ~/bady333/Lineage
          source build/envsetup.sh
          brunch a26

      - name: Upload bady333 to GitHub Nightly Releases
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /home/artisan/bady333/Lineage/out/target/product/a26/recovery.img
            /home/artisan/bady333/Lineage/out/target/product/a26/lineage-23.0-*-UNOFFICIAL-a26.zip
          name: bady333-nightly-a26-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: bady333-Nightly-A26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
